### ISSUE TITLE
Test Language: Javascript 

### ISSUE THREAD

**Issue by Kinnich** [Kinnich/rosetta-io#33]
Apply suit of tests to Javascript:
1. Write Dockerfile in new directory for Javascript/Node.js
2. Set up fixtures to run Ruby tests - using new Ruby class
3. Write Ruby scripts for all test cases:
- [x] TestNullChar
- [x]  TestStdIn
- [x]  TestArgs
- [x]  TestReadJsonFile
- [x] TestWriteJsonToStdout:
- [x]  test_json_array
- [x]  test_json_numbers
- [x]  test_json_objects
- [x]  test_json_objects_with_arrays
- [x]  test_json_object_array
- [x]  test_json_control_chars
- [x]  TestDecodeBase64
- [x]  TestEncodeBase64
- [x]  TestStreamingStdin

**Comment by nicholaides** [comment]
Here's a script that reads line-by-line from stdin. Reading a whole file at once is simpler and doesn't need the `readline` library.

It needs to have the extension `.mjs` instead of `.js` so that it can use top-level `await`.

## `script.mjs`:

```javascript
import * as readline from 'node:readline/promises'

const rl = readline.createInterface({ input: process.stdin })

for await (const line of rl) {
  console.log(line.toUpperCase())
}
```
